version: '3'
services:

  caffeine-tracker-nginx:
    build: ./docker/nginx
    container_name: caffeine-tracker-nginx
    command: nginx -g "daemon off;"
    ports:
        - 8181:80
    volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - caffeine-tracker-app

  caffeine-tracker-mysql:
    image: mysql
    container_name: caffeine-tracker-mysql
    ports:
        - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password

  caffeine-tracker-app:
    build: ./caffeine-tracker-app
    container_name: caffeine-tracker-app
    ports:
        - 9000:80
    volumes:
      - ./caffeine-tracker-app:/var/www
    command: php-fpm
    depends_on:
      - caffeine-tracker-mysql

  caffeine-tracker-ui:
    build: ./caffeine-tracker-ui
    container_name: caffeine-tracker-ui
    ports:
      - 4200:80
    links:
      - caffeine-tracker-app

volumes:
  caffeine-tracker-data: